#!/bin/bash

sudo -u postgres psql -c "CREATE DATABASE onlyoffice;"
sudo -u postgres psql -c "CREATE USER onlyoffice WITH password 'onlyoffice';"
sudo -u postgres psql -c "GRANT ALL privileges ON DATABASE onlyoffice TO onlyoffice;"

systemctl enable supervisord --now
systemctl enable rabbitmq-server --now

/usr/bin/documentserver-configure2.sh

# set firewall port
config show fw_onlyoffice || config set fw_onlyoffice service status enabled TCPPort 8082 access red,green
signal-event firewall-adjust

# expand onlyoffice config
expand-template /etc/nginx/conf.d/onlyoffice-documentserver.conf
expand-template /etc/onlyoffice/documentserver/default.json
supervisorctl restart all

# Enable self-signed cert
grep -q -F "'onlyoffice' => array ( 'verify_peer_off' => TRUE)" /usr/share/nextcloud/config/config.php || sed -i '$i'"'onlyoffice'"' => array ( '"'verify_peer_off'"' => TRUE)' /usr/share/nextcloud/config/config.php

# Install onlyoffice app
sudo -u apache /opt/rh/rh-php71/root/usr/bin/php /usr/share/nextcloud/occ app:install onlyoffice

# Set DocumentServerUrl
export fqdn=`config get SystemName`.`config get DomainName`
export dshost=`config getprop fw_onlyoffice host || echo $fqdn`
sudo -u apache /opt/rh/rh-php71/root/usr/bin/php /usr/share/nextcloud/occ config:app:set onlyoffice DocumentServerUrl --value="https://$dshost:8082/"

# Set token secret
sudo -u apache /opt/rh/rh-php71/root/usr/bin/php /usr/share/nextcloud/occ config:app:set onlyoffice jwt_secret --value="`cat /var/lib/nethserver/secrets/onlyoffice`"

# Enable onlyoffice app
sudo -u apache /opt/rh/rh-php71/root/usr/bin/php /usr/share/nextcloud/occ app:enable onlyoffice
